package mcpapp_test

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	mcpruntime "github.com/theory-cloud/apptheory/runtime/mcp"
	"github.com/theory-cloud/apptheory/testkit"

	"github.com/equaltoai/lesser-body/internal/auth"
	"github.com/equaltoai/lesser-body/internal/lesserapi"
	"github.com/equaltoai/lesser-body/internal/mcpapp"
	"github.com/equaltoai/lesser-body/internal/soulapi"
)

func TestLBM2_EmailSendAndReply_TalkToCommAPI(t *testing.T) {
	const expectedFooter = "---\nThis message was generated by an AI agent in the Lesser Soul ecosystem.\nIt was not written by a human. For more information: https://lessersoul.ai"

	t.Setenv("MCP_SESSION_TABLE", "")
	t.Setenv("JWT_SECRET", "test")
	t.Setenv("LESSER_HOST_INSTANCE_KEY", "instance-key-123")
	installSoulBindingLookup(t, "agent1", "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
	auth.ResetForTests()
	lesserapi.ResetForTests()
	soulapi.ResetForTests()

	const agentID = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
	const tokenUser = "agent1"

	var gotAuth string
	var gotBody map[string]any
	var statusCode int

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.URL.Path == "/api/v1/soul/agents/"+agentID:
			_, _ = w.Write([]byte(`{"version":"1","agent":{"agent_id":"` + agentID + `","domain":"test.example.com","local_id":"agent-bob","status":"active"}}`))
		case r.URL.Path == "/api/v1/soul/agents/"+agentID+"/registration":
			_, _ = w.Write([]byte(`{"version":"3","channels":{},"contactPreferences":{},"boundaries":[{"id":"b1","category":"communication_policy","channel":"email","statement":"no unsolicited"}]}`))
		case r.URL.Path == "/api/v1/notifications" && r.Method == http.MethodGet:
			_, _ = w.Write([]byte(`[
				{
					"id":"notif-1",
					"type":"communication:inbound",
					"channel":"email",
					"messageId":"comm-msg-000",
					"from":{"address":"alice@example.com"},
					"to":{"address":"agent-bob@lessersoul.ai"},
					"subject":"Hello",
					"body":"Original email",
					"receivedAt":"2026-03-10T21:00:00Z"
				}
			]`))
		case r.URL.Path == "/api/v1/soul/comm/send" && r.Method == http.MethodPost:
			gotAuth = r.Header.Get("Authorization")
			body, _ := io.ReadAll(r.Body)
			_ = json.Unmarshal(body, &gotBody)
			w.WriteHeader(statusCode)
			if statusCode == 403 {
				_, _ = w.Write([]byte(`{"error":{"message":"blocked by boundary"}}`))
				return
			}
			_, _ = w.Write([]byte(`{"messageId":"comm-msg-001","status":"sent"}`))
		default:
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte(`{"error":{"message":"not found"}}`))
		}
	}))
	defer server.Close()

	t.Setenv("LESSER_API_BASE_URL", server.URL)
	t.Setenv("LESSER_SOUL_API_BASE_URL", server.URL)
	lesserapi.ResetForTests()
	soulapi.ResetForTests()

	app, err := mcpapp.New("test", "dev")
	if err != nil {
		t.Fatalf("new app: %v", err)
	}
	env := testkit.New()
	token := newTestToken(t, "test", tokenUser, []string{"write"})
	authHeader := "Bearer " + token

	initResp := invokeJSON(t, env, app, map[string][]string{
		"authorization": {authHeader},
	}, &mcpruntime.Request{JSONRPC: "2.0", ID: 1, Method: "initialize"})
	if initResp.Status != 200 {
		t.Fatalf("initialize: status=%d body=%s", initResp.Status, string(initResp.Body))
	}
	sessionID := initResp.Headers["mcp-session-id"][0]

	// email_send should POST to /comm/send with bearer auth and include core fields.
	{
		gotAuth = ""
		gotBody = nil
		statusCode = 200

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_send",
			"arguments": map[string]any{
				"to":        "alice@example.com",
				"subject":   "Hello",
				"body":      "Hi there",
				"inReplyTo": "comm-msg-prev",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 2, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_send: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotAuth != "Bearer instance-key-123" {
			t.Fatalf("expected comm api Authorization=%q, got %q", "Bearer instance-key-123", gotAuth)
		}
		if gotBody["channel"] != "email" || gotBody["agentId"] != agentID {
			t.Fatalf("unexpected comm api body: %+v", gotBody)
		}
		if gotBody["to"] != "alice@example.com" || gotBody["subject"] != "[bot] Hello" || gotBody["body"] != "Hi there\n\n"+expectedFooter {
			t.Fatalf("unexpected comm api payload fields: %+v", gotBody)
		}
		idempotencyKey, _ := gotBody["idempotencyKey"].(string)
		if strings.TrimSpace(idempotencyKey) == "" {
			t.Fatalf("expected generated idempotencyKey, got %+v", gotBody)
		}
		if gotBody["inReplyTo"] != "comm-msg-prev" {
			t.Fatalf("expected inReplyTo=comm-msg-prev, got %+v", gotBody)
		}

		var rpc mcpruntime.Response
		_ = json.Unmarshal(resp.Body, &rpc)
		if rpc.Error != nil {
			t.Fatalf("email_send rpc error: %+v", rpc.Error)
		}
		var out mcpruntime.ToolResult
		{
			b, _ := json.Marshal(rpc.Result)
			_ = json.Unmarshal(b, &out)
		}
		data, _ := out.StructuredContent["data"].(map[string]any)
		if data["messageId"] != "comm-msg-001" || data["status"] != "sent" {
			t.Fatalf("unexpected tool data: %+v", data)
		}
		if data["idempotencyKey"] != idempotencyKey {
			t.Fatalf("expected tool data to include generated idempotencyKey, got %+v", data)
		}
		if data["inReplyTo"] != "comm-msg-prev" {
			t.Fatalf("expected tool data to include inReplyTo, got %+v", data)
		}
	}

	{
		gotAuth = ""
		gotBody = nil
		statusCode = 200

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_send",
			"arguments": map[string]any{
				"to":      "alice@example.com",
				"subject": "Empty body check",
				"body":    "",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 22, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_send empty body: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotBody["body"] != expectedFooter {
			t.Fatalf("expected footer-only email body, got %+v", gotBody)
		}
		if gotBody["subject"] != "[bot] Empty body check" {
			t.Fatalf("expected prefixed subject for empty body case, got %+v", gotBody)
		}
	}

	// email_reply should surface boundary violations as tool errors (isError + structured error code).
	{
		gotAuth = ""
		gotBody = nil
		statusCode = 403

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_reply",
			"arguments": map[string]any{
				"messageId": "comm-msg-000",
				"body":      "reply body",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 3, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_reply: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotAuth != "Bearer instance-key-123" {
			t.Fatalf("expected comm api Authorization=%q, got %q", "Bearer instance-key-123", gotAuth)
		}
		if gotBody["inReplyTo"] != "comm-msg-000" {
			t.Fatalf("expected inReplyTo=comm-msg-000, got %+v", gotBody)
		}
		if gotBody["idempotencyKey"] != "comm-msg-000" {
			t.Fatalf("expected idempotencyKey=comm-msg-000, got %+v", gotBody)
		}
		if gotBody["to"] != "alice@example.com" {
			t.Fatalf("expected reply to original sender, got %+v", gotBody)
		}
		if gotBody["subject"] != "[bot] Re: Hello" {
			t.Fatalf("expected derived reply subject, got %+v", gotBody)
		}
		if gotBody["body"] != "reply body\n\n"+expectedFooter {
			t.Fatalf("expected reply body to include disclosure footer, got %+v", gotBody)
		}

		var rpc mcpruntime.Response
		_ = json.Unmarshal(resp.Body, &rpc)
		if rpc.Error != nil {
			t.Fatalf("email_reply rpc error: %+v", rpc.Error)
		}
		var out mcpruntime.ToolResult
		{
			b, _ := json.Marshal(rpc.Result)
			_ = json.Unmarshal(b, &out)
		}
		if !out.IsError {
			t.Fatalf("expected isError tool result, got %+v", out)
		}
		errPayload, _ := out.StructuredContent["error"].(map[string]any)
		if errPayload["code"] != "boundary_violation" {
			t.Fatalf("expected boundary_violation, got %+v", errPayload)
		}
		if !strings.Contains(strings.ToLower(errPayload["message"].(string)), "blocked") {
			t.Fatalf("expected error message to mention blocked, got %+v", errPayload)
		}
	}
}
