package mcpapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	mcpruntime "github.com/theory-cloud/apptheory/v3/runtime/mcp"
	"github.com/theory-cloud/apptheory/v3/testkit"

	"github.com/equaltoai/lesser-body/internal/auth"
	"github.com/equaltoai/lesser-body/internal/lesserapi"
	"github.com/equaltoai/lesser-body/internal/mcpapp"
	"github.com/equaltoai/lesser-body/internal/soulapi"
	"github.com/equaltoai/lesser-body/internal/trustconfig"
)

func TestLBM2_EmailSendAndReply_TalkToCommAPI(t *testing.T) {
	const expectedFooter = "---\nThis message was generated by an AI agent in the Lesser Soul ecosystem.\nIt was not written by a human. For more information: https://lessersoul.ai"

	t.Setenv("MCP_SESSION_TABLE", "")
	t.Setenv("JWT_SECRET", "test")
	t.Setenv("LESSER_HOST_INSTANCE_KEY", "instance-key-123")
	installSoulBindingLookup(t, "agent1", "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
	auth.ResetForTests()
	lesserapi.ResetForTests()
	soulapi.ResetForTests()
	restoreTrustConfig := mcpapp.SetLoadEffectiveTrustConfigForTests(func(context.Context) (*trustconfig.Effective, error) {
		return &trustconfig.Effective{}, nil
	})
	t.Cleanup(restoreTrustConfig)

	const agentID = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
	const tokenUser = "agent1"
	const canonicalEmail = "agent-bob.simulacrum@lessersoul.ai"

	var gotAuth string
	var gotContactabilityAuth string
	var gotBody map[string]any
	var statusCode int

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.URL.Path == "/api/v1/souls/bound/me":
			_, _ = w.Write([]byte(boundSelfResponse(agentID, "agent1", "test.example.com", "agent-bob")))
		case r.URL.Path == "/api/v1/soul/agents/"+agentID:
			_, _ = w.Write([]byte(`{"version":"1","agent":{"agent_id":"` + agentID + `","domain":"test.example.com","local_id":"agent-bob","status":"active"}}`))
		case r.URL.Path == "/api/v1/soul/agents/"+agentID+"/registration":
			_, _ = w.Write([]byte(`{"version":"3","channels":{"email":{"address":"` + canonicalEmail + `","capabilities":["email-send","email-read","email-manage"]}},"contactPreferences":{},"boundaries":[{"id":"b1","category":"communication_policy","channel":"email","statement":"no unsolicited"}]}`))
		case r.URL.Path == "/api/v1/soul/comm/contactability/"+agentID:
			gotContactabilityAuth = r.Header.Get("Authorization")
			_, _ = w.Write([]byte(`{` + hostedBoundSoulPolicyJSON("not_entitled", false, false) + `,"channels":[{"channelType":"email","sendAllowed":true,"receiveAllowed":true}]}`))
		case r.URL.Path == "/api/v1/soul/comm/send" && r.Method == http.MethodPost:
			gotAuth = r.Header.Get("Authorization")
			body, _ := io.ReadAll(r.Body)
			_ = json.Unmarshal(body, &gotBody)
			w.WriteHeader(statusCode)
			if statusCode == 403 {
				_, _ = w.Write([]byte(`{"error":{"message":"blocked by boundary"}}`))
				return
			}
			_, _ = w.Write([]byte(`{"messageId":"comm-msg-001","status":"sent"}`))
		case r.URL.Path == "/api/v1/soul/comm/mailbox/"+agentID+"/messages/comm-delivery-000/reply" && r.Method == http.MethodPost:
			gotAuth = r.Header.Get("Authorization")
			body, _ := io.ReadAll(r.Body)
			_ = json.Unmarshal(body, &gotBody)
			w.WriteHeader(statusCode)
			if statusCode == 403 {
				_, _ = w.Write([]byte(`{"error":{"message":"blocked by boundary"}}`))
				return
			}
			_, _ = w.Write([]byte(`{"messageRef":"comm-delivery-001","deliveryId":"comm-delivery-001","messageId":"comm-msg-001","status":"queued","threadId":"thread-1"}`))
		default:
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte(`{"error":{"message":"not found"}}`))
		}
	}))
	defer server.Close()

	t.Setenv("LESSER_API_BASE_URL", server.URL)
	t.Setenv("LESSER_SOUL_API_BASE_URL", server.URL)
	lesserapi.ResetForTests()
	soulapi.ResetForTests()

	app, err := mcpapp.New("test", "dev")
	if err != nil {
		t.Fatalf("new app: %v", err)
	}
	env := testkit.New()
	token := newTestToken(t, "test", tokenUser, []string{"write"})
	authHeader := "Bearer " + token

	initResp := invokeJSON(t, env, app, map[string][]string{
		"authorization": {authHeader},
	}, &mcpruntime.Request{JSONRPC: "2.0", ID: 1, Method: "initialize"})
	if initResp.Status != 200 {
		t.Fatalf("initialize: status=%d body=%s", initResp.Status, string(initResp.Body))
	}
	sessionID := initResp.Headers["mcp-session-id"][0]

	// email_send should POST to /comm/send with bearer auth and include core fields.
	{
		gotAuth = ""
		gotBody = nil
		statusCode = 200

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_send",
			"arguments": map[string]any{
				"to":             "alice@example.com",
				"subject":        "Hello",
				"body":           "Hi there",
				"idempotencyKey": "email-key-123",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
			"x-request-id":   {"req-email-send-123"},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 2, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_send: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotAuth != "Bearer instance-key-123" {
			t.Fatalf("expected comm api Authorization=%q, got %q", "Bearer instance-key-123", gotAuth)
		}
		if gotContactabilityAuth != "Bearer instance-key-123" {
			t.Fatalf("expected contactability Authorization=%q, got %q", "Bearer instance-key-123", gotContactabilityAuth)
		}
		if gotBody["channel"] != "email" || gotBody["agentId"] != agentID {
			t.Fatalf("unexpected comm api body: %+v", gotBody)
		}
		if gotBody["to"] != "alice@example.com" || gotBody["subject"] != "[bot] Hello" || gotBody["body"] != "Hi there\n\n"+expectedFooter {
			t.Fatalf("unexpected comm api payload fields: %+v", gotBody)
		}
		idempotencyKey, _ := gotBody["idempotencyKey"].(string)
		if idempotencyKey != "email-key-123" {
			t.Fatalf("expected caller idempotencyKey, got %+v", gotBody)
		}
		if _, ok := gotBody["inReplyTo"]; ok {
			t.Fatalf("email_send must not forward inReplyTo; use email_reply for replies, got %+v", gotBody)
		}

		var rpc mcpruntime.Response
		_ = json.Unmarshal(resp.Body, &rpc)
		if rpc.Error != nil {
			t.Fatalf("email_send rpc error: %+v", rpc.Error)
		}
		var out mcpruntime.ToolResult
		{
			b, _ := json.Marshal(rpc.Result)
			_ = json.Unmarshal(b, &out)
		}
		data, _ := out.StructuredContent["data"].(map[string]any)
		if data["messageId"] != "comm-msg-001" || data["status"] != "sent" {
			t.Fatalf("unexpected tool data: %+v", data)
		}
		if data["idempotencyKey"] != idempotencyKey {
			t.Fatalf("expected tool data to include generated idempotencyKey, got %+v", data)
		}
		if _, ok := data["inReplyTo"]; ok {
			t.Fatalf("email_send response must not expose inReplyTo for new sends, got %+v", data)
		}
	}

	// email_send should reject legacy reply/message identity fields locally before Host sees them.
	{
		gotAuth = ""
		gotBody = nil
		statusCode = 200

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_send",
			"arguments": map[string]any{
				"to":        "alice@example.com",
				"subject":   "Legacy messageId footgun",
				"body":      "Hi there",
				"messageId": "comm-delivery-000",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 23, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_send legacy messageId: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotAuth != "" || gotBody != nil {
			t.Fatalf("legacy email_send messageId should fail before Host, auth=%q body=%+v", gotAuth, gotBody)
		}

		var rpc mcpruntime.Response
		_ = json.Unmarshal(resp.Body, &rpc)
		if rpc.Error != nil {
			t.Fatalf("email_send legacy messageId rpc error: %+v", rpc.Error)
		}
		var out mcpruntime.ToolResult
		b, _ := json.Marshal(rpc.Result)
		_ = json.Unmarshal(b, &out)
		if !out.IsError {
			t.Fatalf("expected tool error for legacy email_send messageId, got %+v", out)
		}
		errPayload, _ := out.StructuredContent["error"].(map[string]any)
		if errPayload["code"] != "invalid_request" {
			t.Fatalf("expected invalid_request, got %+v", errPayload)
		}
		if !strings.Contains(strings.ToLower(errPayload["message"].(string)), "email_reply") {
			t.Fatalf("expected error to direct callers to email_reply, got %+v", errPayload)
		}
		details, _ := errPayload["details"].(map[string]any)
		if details["replyTool"] != "email_reply" {
			t.Fatalf("expected replyTool detail, got %+v", errPayload)
		}
	}

	{
		gotAuth = ""
		gotBody = nil
		statusCode = 200

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_send",
			"arguments": map[string]any{
				"to":      "alice@example.com",
				"subject": "Empty body check",
				"body":    "",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 22, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_send empty body: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotBody["body"] != expectedFooter {
			t.Fatalf("expected footer-only email body, got %+v", gotBody)
		}
		if gotBody["subject"] != "[bot] Empty body check" {
			t.Fatalf("expected prefixed subject for empty body case, got %+v", gotBody)
		}
	}

	// email_reply should surface boundary violations as tool errors (isError + structured error code).
	{
		gotAuth = ""
		gotBody = nil
		statusCode = 403

		callParams, _ := json.Marshal(map[string]any{
			"name": "email_reply",
			"arguments": map[string]any{
				"messageId":      "comm-delivery-000",
				"body":           "reply body",
				"subject":        "Follow-up",
				"to":             "ignored@example.com",
				"replyAll":       true,
				"idempotencyKey": "reply-key-123",
			},
		})
		resp := invokeJSON(t, env, app, map[string][]string{
			"authorization":  {authHeader},
			"mcp-session-id": {sessionID},
		}, &mcpruntime.Request{JSONRPC: "2.0", ID: 3, Method: "tools/call", Params: callParams})
		if resp.Status != 200 {
			t.Fatalf("email_reply: status=%d body=%s", resp.Status, string(resp.Body))
		}
		if gotAuth != "Bearer instance-key-123" {
			t.Fatalf("expected comm api Authorization=%q, got %q", "Bearer instance-key-123", gotAuth)
		}
		if _, ok := gotBody["inReplyTo"]; ok {
			t.Fatalf("did not expect body to reconstruct inReplyTo for host-backed reply, got %+v", gotBody)
		}
		if gotBody["idempotencyKey"] != "reply-key-123" {
			t.Fatalf("expected explicit idempotencyKey, got %+v", gotBody)
		}
		if _, ok := gotBody["to"]; ok {
			t.Fatalf("did not expect body to reconstruct recipient for host-backed reply, got %+v", gotBody)
		}
		if gotBody["subject"] != "[bot] Follow-up" {
			t.Fatalf("expected prefixed explicit subject, got %+v", gotBody)
		}
		if gotBody["body"] != "reply body\n\n"+expectedFooter {
			t.Fatalf("expected reply body to include disclosure footer, got %+v", gotBody)
		}

		var rpc mcpruntime.Response
		_ = json.Unmarshal(resp.Body, &rpc)
		if rpc.Error != nil {
			t.Fatalf("email_reply rpc error: %+v", rpc.Error)
		}
		var out mcpruntime.ToolResult
		{
			b, _ := json.Marshal(rpc.Result)
			_ = json.Unmarshal(b, &out)
		}
		if !out.IsError {
			t.Fatalf("expected isError tool result, got %+v", out)
		}
		errPayload, _ := out.StructuredContent["error"].(map[string]any)
		if errPayload["code"] != "boundary_violation" {
			t.Fatalf("expected boundary_violation, got %+v", errPayload)
		}
		if !strings.Contains(strings.ToLower(errPayload["message"].(string)), "blocked") {
			t.Fatalf("expected error message to mention blocked, got %+v", errPayload)
		}
	}
}

func TestBoundBodyOperationPolicyDeniesImplicitAndPublicPaidEmail(t *testing.T) {
	scenarios := []struct {
		name          string
		registration  string
		token         func(testing.TB) string
		wantReason    string
		wantPolicyVer string
	}{
		{
			name:         "bound soul without explicit policy cannot send email",
			registration: `{"version":"3","channels":{"email":{"address":"agent@example.com"}},"contactPreferences":{}}`,
			token: func(tb testing.TB) string {
				return newTestToken(tb, "test", "agent1", []string{"write"})
			},
			wantReason: "capability_policy_denied",
		},
		{
			name:         "public paid oauth caller requires scoped x402 grant",
			registration: `{"version":"3","channels":{"email":{"capabilities":["email-send"]}},"contactPreferences":{},` + boundBodyPolicyJSON("communication.email.send") + `}`,
			token: func(tb testing.TB) string {
				return newTestTokenWithClientClass(tb, "test", "agent1", []string{"write"}, "public_paid")
			},
			wantReason:    "x402_grant_required",
			wantPolicyVer: "2026-05-16",
		},
	}

	for _, scenario := range scenarios {
		t.Run(scenario.name, func(t *testing.T) {
			t.Setenv("MCP_SESSION_TABLE", "")
			t.Setenv("JWT_SECRET", "test")
			t.Setenv("LESSER_HOST_INSTANCE_KEY", "instance-key-123")
			installSoulBindingLookup(t, "agent1", "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
			auth.ResetForTests()
			lesserapi.ResetForTests()
			soulapi.ResetForTests()
			restoreTrustConfig := mcpapp.SetLoadEffectiveTrustConfigForTests(func(context.Context) (*trustconfig.Effective, error) {
				return &trustconfig.Effective{}, nil
			})
			t.Cleanup(restoreTrustConfig)

			const agentID = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
			var commSendCalled bool
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				switch r.URL.Path {
				case "/api/v1/souls/bound/me":
					_, _ = w.Write([]byte(boundSelfResponse(agentID, "agent1", "test.example.com", "agent-bob")))
				case "/api/v1/soul/agents/" + agentID:
					_, _ = w.Write([]byte(`{"version":"1","agent":{"agent_id":"` + agentID + `","domain":"test.example.com","local_id":"agent-bob","status":"active"}}`))
				case "/api/v1/soul/agents/" + agentID + "/registration":
					_, _ = w.Write([]byte(scenario.registration))
				case "/api/v1/soul/comm/send":
					commSendCalled = true
					_, _ = w.Write([]byte(`{"messageId":"comm-msg-001","status":"sent"}`))
				default:
					w.WriteHeader(http.StatusNotFound)
					_, _ = w.Write([]byte(`{"error":{"message":"not found"}}`))
				}
			}))
			defer server.Close()

			t.Setenv("LESSER_API_BASE_URL", server.URL)
			t.Setenv("LESSER_SOUL_API_BASE_URL", server.URL)
			lesserapi.ResetForTests()
			soulapi.ResetForTests()

			app, err := mcpapp.New("test", "dev")
			if err != nil {
				t.Fatalf("new app: %v", err)
			}
			env := testkit.New()
			authHeader := "Bearer " + scenario.token(t)
			initResp := invokeJSON(t, env, app, map[string][]string{
				"authorization": {authHeader},
			}, &mcpruntime.Request{JSONRPC: "2.0", ID: 1, Method: "initialize"})
			if initResp.Status != 200 {
				t.Fatalf("initialize: status=%d body=%s", initResp.Status, string(initResp.Body))
			}
			sessionID := initResp.Headers["mcp-session-id"][0]

			callParams, _ := json.Marshal(map[string]any{
				"name": "email_send",
				"arguments": map[string]any{
					"to":      "alice@example.com",
					"subject": "Hello",
					"body":    "Hi",
				},
			})
			resp := invokeJSON(t, env, app, map[string][]string{
				"authorization":  {authHeader},
				"mcp-session-id": {sessionID},
			}, &mcpruntime.Request{JSONRPC: "2.0", ID: 2, Method: "tools/call", Params: callParams})
			if resp.Status != 200 {
				t.Fatalf("email_send: status=%d body=%s", resp.Status, string(resp.Body))
			}
			if commSendCalled {
				t.Fatalf("denied operation must fail before lesser-host comm/send")
			}

			var rpc mcpruntime.Response
			_ = json.Unmarshal(resp.Body, &rpc)
			if rpc.Error != nil {
				t.Fatalf("email_send rpc error: %+v", rpc.Error)
			}
			var out mcpruntime.ToolResult
			b, _ := json.Marshal(rpc.Result)
			_ = json.Unmarshal(b, &out)
			if !out.IsError {
				t.Fatalf("expected operation_not_allowed tool error, got %+v", out)
			}
			errPayload, _ := out.StructuredContent["error"].(map[string]any)
			if errPayload["code"] != "operation_not_allowed" {
				t.Fatalf("expected operation_not_allowed, got %+v", errPayload)
			}
			details, _ := errPayload["details"].(map[string]any)
			if details["reason"] != scenario.wantReason || details["operation"] != "communication.email.send" {
				t.Fatalf("unexpected sanitized denial details: %+v", details)
			}
			if details["provider"] != nil || details["paymentEvidence"] != nil || details["tenant"] != nil || details["wallet"] != nil {
				t.Fatalf("denial details must not expose provider/payment/tenant/wallet data: %+v", details)
			}
			if scenario.wantPolicyVer != "" && details["policyVersion"] != scenario.wantPolicyVer {
				t.Fatalf("expected policyVersion=%q, got %+v", scenario.wantPolicyVer, details)
			}
		})
	}
}
