package mcpserver

import (
	"context"
	"encoding/json"
	"net/url"
	"strings"

	"github.com/equaltoai/lesser-body/internal/soulapi"
	mcpruntime "github.com/theory-cloud/apptheory/runtime/mcp"
)

const emailDisclosureFooter = "---\nThis message was generated by an AI agent in the Lesser Soul ecosystem.\nIt was not written by a human. For more information: https://lessersoul.ai"

func handleEmailSend(ctx context.Context, args json.RawMessage) (*mcpruntime.ToolResult, error) {
	return handleEmailSendWithProgress(ctx, args, nil)
}

func handleEmailSendStreaming(ctx context.Context, args json.RawMessage, emit func(mcpruntime.SSEEvent)) (*mcpruntime.ToolResult, error) {
	return handleEmailSendWithProgress(ctx, args, emit)
}

func handleEmailSendWithProgress(ctx context.Context, args json.RawMessage, emit func(mcpruntime.SSEEvent)) (*mcpruntime.ToolResult, error) {
	var in struct {
		To        string   `json:"to"`
		Subject   string   `json:"subject"`
		Body      string   `json:"body"`
		CC        []string `json:"cc,omitempty"`
		BCC       []string `json:"bcc,omitempty"`
		ReplyTo   string   `json:"replyTo,omitempty"`
		MessageID string   `json:"messageId,omitempty"`
		InReplyTo string   `json:"inReplyTo,omitempty"`
	}
	if err := json.Unmarshal(args, &in); err != nil {
		return toolErrorResult("invalid_request", "invalid args: "+err.Error(), 400, nil)
	}
	in.To = strings.TrimSpace(in.To)
	in.Subject = strings.TrimSpace(in.Subject)
	in.Body = strings.TrimSpace(in.Body)
	in.ReplyTo = strings.TrimSpace(in.ReplyTo)
	replyRef, err := resolveCommReplyReference(in.MessageID, in.InReplyTo)
	if err != nil {
		return toolErrorResult("invalid_request", err.Error(), 400, nil)
	}
	if in.To == "" || in.Subject == "" {
		return toolErrorResult("invalid_request", "to and subject are required", 400, nil)
	}
	in.Subject = ensureBotDisclosurePrefix(in.Subject)
	in.Body = ensureEmailDisclosureFooter(in.Body)
	idempotencyKey := resolveOutboundCommIdempotencyKey(ctx, in.MessageID)

	deps, res, err := loadCommSendDependencies(ctx, "email")
	if res != nil || err != nil {
		return res, err
	}

	emitCommProgress(emit, 1, 2, "sending email")

	body := map[string]any{
		"to":      in.To,
		"subject": in.Subject,
		"body":    in.Body,
		"cc":      normalizeStringSlice(in.CC),
		"bcc":     normalizeStringSlice(in.BCC),
		"replyTo": in.ReplyTo,
	}
	if body["cc"] == nil {
		delete(body, "cc")
	}
	if body["bcc"] == nil {
		delete(body, "bcc")
	}
	if strings.TrimSpace(in.ReplyTo) == "" {
		delete(body, "replyTo")
	}
	if replyRef != "" {
		body["inReplyTo"] = replyRef
	}

	normalized, err := sendOutboundComm(ctx, deps, "email", body, idempotencyKey)
	if err != nil {
		return commToolResultFromError(err)
	}
	emitCommProgress(emit, 2, 2, "email queued")
	if replyRef != "" {
		normalized["inReplyTo"] = replyRef
	}
	return toolJSONResult(normalized)
}

func handleEmailReply(ctx context.Context, args json.RawMessage) (*mcpruntime.ToolResult, error) {
	return handleEmailReplyWithProgress(ctx, args, nil)
}

func handleEmailReplyStreaming(ctx context.Context, args json.RawMessage, emit func(mcpruntime.SSEEvent)) (*mcpruntime.ToolResult, error) {
	return handleEmailReplyWithProgress(ctx, args, emit)
}

func handleEmailReplyWithProgress(ctx context.Context, args json.RawMessage, emit func(mcpruntime.SSEEvent)) (*mcpruntime.ToolResult, error) {
	var in struct {
		MessageID      string   `json:"messageId"`
		Body           string   `json:"body"`
		To             string   `json:"to,omitempty"`
		Subject        string   `json:"subject,omitempty"`
		CC             []string `json:"cc,omitempty"`
		BCC            []string `json:"bcc,omitempty"`
		ReplyTo        string   `json:"replyTo,omitempty"`
		ReplyAll       bool     `json:"replyAll,omitempty"`
		IdempotencyKey string   `json:"idempotencyKey,omitempty"`
	}
	if err := json.Unmarshal(args, &in); err != nil {
		return toolErrorResult("invalid_request", "invalid args: "+err.Error(), 400, nil)
	}
	in.MessageID = strings.TrimSpace(in.MessageID)
	in.Body = strings.TrimSpace(in.Body)
	in.To = strings.TrimSpace(in.To)
	in.Subject = strings.TrimSpace(in.Subject)
	in.ReplyTo = strings.TrimSpace(in.ReplyTo)
	if in.MessageID == "" {
		return toolErrorResult("invalid_request", "messageId is required", 400, nil)
	}
	if in.Body == "" {
		return toolErrorResult("invalid_request", "body is required", 400, nil)
	}

	deps, err := loadCommMailboxDependencies(ctx)
	if err != nil {
		return commMailboxToolResultFromError(err)
	}

	payload := map[string]any{
		"body":           ensureEmailDisclosureFooter(in.Body),
		"idempotencyKey": outboundIdempotencyKey(ctx, in.IdempotencyKey),
	}
	if in.Subject != "" {
		payload["subject"] = ensureBotDisclosurePrefix(in.Subject)
	}
	if cc := normalizeStringSlice(in.CC); cc != nil {
		payload["cc"] = cc
	}
	if bcc := normalizeStringSlice(in.BCC); bcc != nil {
		payload["bcc"] = bcc
	}
	if in.ReplyTo != "" {
		payload["replyTo"] = in.ReplyTo
	}

	emitCommProgress(emit, 1, 2, "sending reply")
	out, err := replyHostMailboxMessage(ctx, deps, in.MessageID, payload)
	if err != nil {
		return commMailboxToolResultFromError(err)
	}
	emitCommProgress(emit, 2, 2, "reply queued")
	out["inReplyTo"] = in.MessageID
	out["idempotencyKey"] = payload["idempotencyKey"]
	out["replyResolvedByHost"] = true
	if in.To != "" || in.ReplyAll {
		advisory, _ := out["advisory"].(map[string]any)
		if advisory == nil {
			advisory = map[string]any{}
		}
		if in.To != "" {
			advisory["toOverrideIgnored"] = true
		}
		if in.ReplyAll {
			advisory["replyAllRequested"] = true
			advisory["replyAllResolvedByHost"] = false
		}
		out["advisory"] = advisory
	}
	return toolJSONResult(out)
}

func emailReplyRecipient(notification map[string]any) string {
	from := commFrom(notification)
	for _, key := range []string{"address", "email", "identifier"} {
		if value, _ := from[key].(string); strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func emailReplySubject(notification map[string]any) string {
	subject := strings.TrimSpace(commSubject(notification))
	if subject == "" {
		return "Re: (no subject)"
	}
	lower := strings.ToLower(subject)
	if strings.HasPrefix(lower, "re:") {
		return subject
	}
	return "Re: " + subject
}

func normalizeCommSendResult(raw any, advisory map[string]any) map[string]any {
	out := map[string]any{
		"messageId": "",
		"status":    "",
		"result":    raw,
	}

	if m, ok := raw.(map[string]any); ok {
		messageRef := strings.TrimSpace(stringFromMap(m, "messageRef"))
		deliveryID := strings.TrimSpace(stringFromMap(m, "deliveryId"))
		hostMessageID := strings.TrimSpace(stringFromMap(m, "messageId"))
		if messageRef == "" {
			messageRef = deliveryID
		}
		if messageRef == "" {
			messageRef = hostMessageID
		}
		if messageRef == "" {
			messageRef = strings.TrimSpace(stringFromMap(m, "message_id"))
		}
		if messageRef == "" {
			messageRef = strings.TrimSpace(stringFromMap(m, "id"))
		}
		out["messageId"] = messageRef
		if messageRef != "" {
			out["messageRef"] = messageRef
		}
		if deliveryID != "" {
			out["deliveryId"] = deliveryID
		}
		if hostMessageID != "" {
			out["hostMessageId"] = hostMessageID
		}
		for _, key := range []string{"threadId", "status", "channel", "agentId", "to", "provider", "providerMessageId", "createdAt"} {
			if v, ok := m[key]; ok {
				out[key] = v
			}
		}
	}

	if len(advisory) > 0 {
		out["advisory"] = advisory
	}

	return out
}

func maybeHydrateCommStatus(ctx context.Context, client *soulapi.Client, bearerToken string, payload map[string]any) error {
	if client == nil || payload == nil {
		return nil
	}
	messageID, _ := payload["hostMessageId"].(string)
	messageID = strings.TrimSpace(messageID)
	if messageID == "" {
		messageID, _ = payload["messageId"].(string)
		messageID = strings.TrimSpace(messageID)
	}
	if messageID == "" {
		return nil
	}
	status, _ := payload["status"].(string)
	if strings.TrimSpace(status) != "" {
		return nil
	}

	out, err := client.DoJSON(ctx, "GET", "/api/v1/soul/comm/status/"+url.PathEscape(messageID), nil, bearerToken, nil)
	if err != nil {
		return err
	}
	m, ok := out.(map[string]any)
	if !ok {
		return nil
	}
	if v, _ := m["status"].(string); strings.TrimSpace(v) != "" {
		payload["status"] = strings.TrimSpace(v)
	}
	payload["delivery"] = m
	return nil
}

func normalizeStringSlice(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, 0, len(in))
	seen := map[string]bool{}
	for _, v := range in {
		v = strings.TrimSpace(v)
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func ensureEmailDisclosureFooter(body string) string {
	body = strings.TrimSpace(body)
	if strings.HasSuffix(body, emailDisclosureFooter) {
		return body
	}
	if body == "" {
		return emailDisclosureFooter
	}
	return body + "\n\n" + emailDisclosureFooter
}
