package installpack

const installMarkerPath = ".lesser-body/install-marker.json"

type layout struct {
	profile Profile
	files   []fileSpec
}

type fileSpec struct {
	path         string
	role         string
	kind         string
	mediaType    string
	required     bool
	description  string
	templateName string
	template     string
	renderer     func(templateData) ([]byte, error)
}

type renderedFile struct {
	spec fileSpec
	body []byte
}

type templateData struct {
	Profile           string
	StageDomain       string
	Actor             string
	Namespace         string
	Account           string
	PackID            string
	PackDigest        string
	MCPServerName     string
	MCPEndpointURL    string
	OAuthMetadataURL  string
	AuthorizationURL  string
	AgentSoul         string
	AgentInstructions string
}

func defaultLayouts() map[Profile]layout {
	return map[Profile]layout{
		ProfileClaudeCode: claudeCodeLayout(),
		ProfileCodex:      codexLayout(),
	}
}

func claudeCodeLayout() layout {
	return layout{profile: ProfileClaudeCode, files: []fileSpec{
		mcpJSONSpec(),
		{
			path:         "CLAUDE.md",
			role:         "agent_instructions",
			kind:         "instructions",
			mediaType:    "text/markdown; charset=utf-8",
			required:     true,
			description:  "Claude Code local instructions rendered from explicit Ba install-pack inputs.",
			templateName: "claude_code_instructions.v1",
			template: `# Lesser agent {{.Actor}}

This local workspace is configured to use the Lesser MCP server ` + "`{{.MCPServerName}}`" + `.

- MCP endpoint: ` + "`{{.MCPEndpointURL}}`" + `
- OAuth: use Lesser OAuth protected-resource discovery at ` + "`{{.OAuthMetadataURL}}`" + `.
- Do not add hardcoded bearer tokens, access leases, or static Authorization headers to this pack.

## Agent soul

{{.AgentSoul}}

## Agent instructions

{{.AgentInstructions}}
`,
		},
		installMarkerSpec(),
		installGuideSpec(),
	}}
}

func codexLayout() layout {
	return layout{profile: ProfileCodex, files: []fileSpec{
		mcpJSONSpec(),
		{
			path:         ".codex/config.toml",
			role:         "codex_mcp_config",
			kind:         "config",
			mediaType:    "text/toml; charset=utf-8",
			required:     true,
			description:  "Codex MCP server config snippet using the standard Lesser OAuth HTTP endpoint.",
			templateName: "codex_config.v1",
			template: `# Generated by lesser-body Ba install-pack renderer.
# Uses Lesser OAuth discovery through the HTTP MCP endpoint; no static token is embedded.

[mcp_servers."{{.MCPServerName}}"]
url = "{{.MCPEndpointURL}}"
`,
		},
		{
			path:         "AGENTS.md",
			role:         "agent_instructions",
			kind:         "instructions",
			mediaType:    "text/markdown; charset=utf-8",
			required:     true,
			description:  "Codex local instructions rendered from explicit Ba install-pack inputs.",
			templateName: "codex_agents_instructions.v1",
			template: `# Lesser agent {{.Actor}}

Use the MCP server ` + "`{{.MCPServerName}}`" + ` for this Lesser agent.

- MCP endpoint: ` + "`{{.MCPEndpointURL}}`" + `
- OAuth: use Lesser OAuth protected-resource discovery at ` + "`{{.OAuthMetadataURL}}`" + `.
- Do not add hardcoded bearer tokens, access leases, or static Authorization headers to this pack.

## Agent soul

{{.AgentSoul}}

## Agent instructions

{{.AgentInstructions}}
`,
		},
		installMarkerSpec(),
		installGuideSpec(),
	}}
}

func mcpJSONSpec() fileSpec {
	return fileSpec{
		path:         ".mcp.json",
		role:         "mcp_client_config",
		kind:         "config",
		mediaType:    "application/json",
		required:     true,
		description:  "MCP HTTP client config pointing at the actor-specific Lesser endpoint; auth is discovered through standard Lesser OAuth metadata.",
		templateName: "mcp_json.v1",
		renderer:     renderMCPJSON,
	}
}

func installMarkerSpec() fileSpec {
	return fileSpec{
		path:         installMarkerPath,
		role:         "install_marker",
		kind:         "metadata",
		mediaType:    "application/json",
		required:     true,
		description:  "Deterministic install marker metadata for local verification and safe re-application.",
		templateName: "install_marker.v1",
		renderer:     renderInstallMarker,
	}
}

func installGuideSpec() fileSpec {
	return fileSpec{
		path:         "INSTALL.md",
		role:         "merge_instructions",
		kind:         "documentation",
		mediaType:    "text/markdown; charset=utf-8",
		required:     true,
		description:  "Human-readable local merge and checksum verification guidance for the pack.",
		templateName: "install_guide.v1",
		template: `# Lesser local install pack

Profile: ` + "`{{.Profile}}`" + `  
MCP server name: ` + "`{{.MCPServerName}}`" + `  
MCP endpoint: ` + "`{{.MCPEndpointURL}}`" + `

## Verify before merging

1. Read ` + "`MANIFEST.json`" + `.
2. For every ` + "`manifest_entries[]`" + ` item, compute SHA-256 over the ZIP entry bytes and compare it to ` + "`checksum`" + `.
3. Merge only the required config/instruction files that match the manifest.

## Authentication posture

The rendered MCP config uses the actor-specific HTTP endpoint and standard Lesser OAuth protected-resource metadata:

` + "`{{.OAuthMetadataURL}}`" + `

This pack intentionally contains no bearer token, access lease, client secret, installer grant URL, or raw grant token.
`,
	}
}

func (l layout) mergeInstructions(serverName string) []MergeInstruction {
	switch l.profile {
	case ProfileClaudeCode:
		return []MergeInstruction{
			{Path: ".mcp.json", Action: "merge_mcp_server", Description: "Merge the mcpServers entry keyed by " + serverName + " into the local Claude Code MCP config."},
			{Path: "CLAUDE.md", Action: "review_then_write", Description: "Review the rendered Claude Code instructions before writing or replacing local instructions."},
			{Path: installMarkerPath, Action: "write_marker", Description: "Write after checksum verification so future installs can identify this pack."},
		}
	case ProfileCodex:
		return []MergeInstruction{
			{Path: ".mcp.json", Action: "merge_mcp_server", Description: "Merge the mcpServers entry keyed by " + serverName + " into any JSON MCP config used by the local host."},
			{Path: ".codex/config.toml", Action: "merge_mcp_server", Description: "Merge the mcp_servers table for " + serverName + " into Codex config."},
			{Path: "AGENTS.md", Action: "review_then_write", Description: "Review the rendered Codex instructions before writing or replacing local instructions."},
			{Path: installMarkerPath, Action: "write_marker", Description: "Write after checksum verification so future installs can identify this pack."},
		}
	default:
		return nil
	}
}
